language: R
sudo: false
cache: packages
warnings_are_errors: false

matrix:
  include:
    - os: linux
      r: release

    - os: linux
      r: oldrel
      after_success:
      - echo skipping source packaging on linux/oldrel
      
    - os: linux
      r: devel
      after_success:
      - echo skipping source packaging on linux/devel

    - os: osx
      r: release
      if: branch = master
      
    - os: osx
      osx_image: xcode6.4
      r: oldrel
      if: branch = master

r_packages:
 -- numDeriv

r_github_packages:
 -- r-lib/covr

after_success:
 -- test $TRAVIS_OS_NAME == "linux" && Rscript -e 'covr::coveralls()'
